#
# (C) 2021 CRXSS TECHNOLOGY LIMITED
#

title: CRXSS
subtitle: Technology

description: >-
  Something

baseurl: ""
url: ""

author:
email: info@crxsstech.uk
country: United Kingdom
phone: (716) 555-5555

tiles-source: pages
tiles-count: 6

500px_url:
facebook_url:
github_url: https://github.com
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com
twitter_url: https://twitter.com

contact_form_action: https://formspree.io/f/mwkaeqoo


# Build Settings

remote_theme: andrewbanchich/forty-jekyll-theme

markdown: kramdown

sass:
  style: compressed
